const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{play: 0},
	{Touch: 0},
	{Sprite2: 0},
	{Solid: 0},
	{chao: 0},
	{Bullet: 0},
	{cobra: 0},
	{moeda: 0},
	{Sprite3: 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{player: 0},
	{parede2: 0},
	{parede1: 0},
	{Sprite4: 0},
	{Keyboard: 0},
	{parede: 0},
	{Particles: 0},
	{Particulamoeda: 0},
	{Particles2: 0},
	{Sprite5: 0},
	{Text: 0},
	{Áudio: 0},
	{pontos: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	chao: class extends self.ITiledBackgroundInstance {},
	cobra: class extends self.ISpriteInstance {},
	moeda: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	parede2: class extends self.ISpriteInstance {},
	parede1: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	parede: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particulamoeda: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {}
}